//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_ER3_hw.WebService_ZHELLOWORLD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="WebService_ZHELLOWORLD.Z_HELLO_WORLD_2")]
    public interface Z_HELLO_WORLD_2 {
        
        // CODEGEN: Generating message contract since the operation Z_HELLO_WORLD is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse1 Z_HELLO_WORLD(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse1> Z_HELLO_WORLDAsync(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_HELLO_WORLD : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_HELLO_WORLDResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
                this.RaisePropertyChanged("RESULT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_HELLO_WORLDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD Z_HELLO_WORLD;
        
        public Z_HELLO_WORLDRequest() {
        }
        
        public Z_HELLO_WORLDRequest(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD Z_HELLO_WORLD) {
            this.Z_HELLO_WORLD = Z_HELLO_WORLD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_HELLO_WORLDResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse Z_HELLO_WORLDResponse;
        
        public Z_HELLO_WORLDResponse1() {
        }
        
        public Z_HELLO_WORLDResponse1(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse Z_HELLO_WORLDResponse) {
            this.Z_HELLO_WORLDResponse = Z_HELLO_WORLDResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_HELLO_WORLD_2Channel : WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD_2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_HELLO_WORLD_2Client : System.ServiceModel.ClientBase<WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD_2>, WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD_2 {
        
        public Z_HELLO_WORLD_2Client() {
        }
        
        public Z_HELLO_WORLD_2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_HELLO_WORLD_2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_HELLO_WORLD_2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_HELLO_WORLD_2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse1 WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD_2.Z_HELLO_WORLD(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest request) {
            return base.Channel.Z_HELLO_WORLD(request);
        }
        
        public WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse Z_HELLO_WORLD(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD Z_HELLO_WORLD1) {
            WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest inValue = new WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest();
            inValue.Z_HELLO_WORLD = Z_HELLO_WORLD1;
            WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse1 retVal = ((WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD_2)(this)).Z_HELLO_WORLD(inValue);
            return retVal.Z_HELLO_WORLDResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse1> WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD_2.Z_HELLO_WORLDAsync(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest request) {
            return base.Channel.Z_HELLO_WORLDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDResponse1> Z_HELLO_WORLDAsync(WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD Z_HELLO_WORLD) {
            WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest inValue = new WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLDRequest();
            inValue.Z_HELLO_WORLD = Z_HELLO_WORLD;
            return ((WS_ER3_hw.WebService_ZHELLOWORLD.Z_HELLO_WORLD_2)(this)).Z_HELLO_WORLDAsync(inValue);
        }
    }
}
