//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WS_ER3_hw.pl.aquael.er3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'EndpointReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/08/addressing' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Z_HELLO_WORLD_2", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_HELLO_WORLD_2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Z_HELLO_WORLDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Z_HELLO_WORLD_2() {
            this.Url = global::WS_ER3_hw.Properties.Settings.Default.WS_ER3_hw_pl_aquael_er3_Z_HELLO_WORLD_2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Z_HELLO_WORLDCompletedEventHandler Z_HELLO_WORLDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Z_HELLO_WORLDResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public Z_HELLO_WORLDResponse Z_HELLO_WORLD([System.Xml.Serialization.XmlElementAttribute("Z_HELLO_WORLD", Namespace="urn:sap-com:document:sap:rfc:functions")] Z_HELLO_WORLD Z_HELLO_WORLD1) {
            object[] results = this.Invoke("Z_HELLO_WORLD", new object[] {
                        Z_HELLO_WORLD1});
            return ((Z_HELLO_WORLDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Z_HELLO_WORLDAsync(Z_HELLO_WORLD Z_HELLO_WORLD1) {
            this.Z_HELLO_WORLDAsync(Z_HELLO_WORLD1, null);
        }
        
        /// <remarks/>
        public void Z_HELLO_WORLDAsync(Z_HELLO_WORLD Z_HELLO_WORLD1, object userState) {
            if ((this.Z_HELLO_WORLDOperationCompleted == null)) {
                this.Z_HELLO_WORLDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_HELLO_WORLDOperationCompleted);
            }
            this.InvokeAsync("Z_HELLO_WORLD", new object[] {
                        Z_HELLO_WORLD1}, this.Z_HELLO_WORLDOperationCompleted, userState);
        }
        
        private void OnZ_HELLO_WORLDOperationCompleted(object arg) {
            if ((this.Z_HELLO_WORLDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_HELLO_WORLDCompleted(this, new Z_HELLO_WORLDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_HELLO_WORLD {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_HELLO_WORLDResponse {
        
        private string rESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void Z_HELLO_WORLDCompletedEventHandler(object sender, Z_HELLO_WORLDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_HELLO_WORLDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_HELLO_WORLDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Z_HELLO_WORLDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Z_HELLO_WORLDResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591